#### This is my first AI class in Ibadan

In [1]:
1 = 2

SyntaxError: can't assign to literal (<ipython-input-1-c0ab9e3898ea>, line 1)

In [3]:
a=1
b=2
a>b

False

In [4]:
a=1
b=2
a<b

True

In [6]:
x=5
x-6

-1

In [7]:
x=20
y=15
x*y

300

In [9]:
x=20
y=15
(x*y)**2

90000

In [10]:
### Below are python lessons 

In [12]:
#'addition - X+5'
#'Subtraction - x-5'
#'Multiplication - x*5'
#'Division  (Float) x/5'
#'Modulus  x%5'

In [13]:
str((1,2,3))

'(1, 2, 3)'

In [14]:
bool("TRUE, FALSE")

True

In [15]:
bool("2,4")

True

In [16]:
type("True")

str

In [18]:
type(True)

bool

In [22]:
a=bool(("True", "False"))

In [24]:
type(a)

bool

In [25]:
int(a)

1

In [26]:
help(float)

Help on class float in module builtins:

class float(object)
 |  float(x=0, /)
 |  
 |  Convert a string or number to a floating point number, if possible.
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __format__(self, format_spec, /)
 |      Formats the float according to format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getnewargs__(self, /)
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __int__(self, /)
 |      int(sel

In [36]:
my_string="learning"
print('I love', my_string + " "+ "and"+  " " "reading")

I love learning and reading


In [33]:
help(float)

Help on class float in module builtins:

class float(object)
 |  float(x=0, /)
 |  
 |  Convert a string or number to a floating point number, if possible.
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __format__(self, format_spec, /)
 |      Formats the float according to format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getnewargs__(self, /)
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __int__(self, /)
 |      int(sel

In [48]:
my_string="Adeniyi"
print('my details are:', my_string+ " " + "Osun"+ " " "State")

my details are: Adeniyi Osun State


In [7]:
a= "are"
b= "mine"
c= "forever"
my_list = ["these", "list", a, b, c]
print(my_list)

['these', 'list', 'are', 'mine', 'forever']


In [15]:
#This is to form a list of lists

my_list2=[[1,2,6,9], [6,5,9,3], ["a,b,c,d"]]
print(my_list2)

[[1, 2, 6, 9], [6, 5, 9, 3], ['a,b,c,d']]


In [10]:
my_list[0]

'these'

In [11]:
my_list[2]

'are'

In [12]:
my_list[-1]

'forever'

In [13]:
my_list[-2]

'mine'

In [18]:
my_list2[1][-2]

9

In [19]:
my_list[1:4]  #This code is used to index a range from our list, if we need Observations 1 to 3 then we index 1:4

['list', 'are', 'mine']

In [20]:
my_list[1:]

['list', 'are', 'mine', 'forever']

In [21]:
my_list[:]

['these', 'list', 'are', 'mine', 'forever']

In [22]:
my_list[:2]   #this type of indexing or range finding means(we didnt specify the starting point. Same can be done for no end)

['these', 'list']

In [23]:
my_list2[:]

[[1, 2, 6, 9], [6, 5, 9, 3], ['a,b,c,d']]

In [33]:
my_list2 >4

TypeError: '>' not supported between instances of 'list' and 'int'

In [88]:
new_list = [1, 2, 3, 4, 5, 5, 5, 5, 6, 7, 8, 9, 10]
new_list

[1, 2, 3, 4, 5, 5, 5, 5, 6, 7, 8, 9, 10]

In [89]:
new_list.index(10)

12

In [90]:
new_list.index(11)

ValueError: 11 is not in list

In [91]:
new_list.index(1)

0

In [92]:
new_list.index(2)

1

In [93]:
#Here, this is the method to pop up suggestion to be used on python (by new_list. then press tab key or shift+tab) pressing shift+tab keys allow user to read documentation on python

new_list.index      

<function list.index(value, start=0, stop=9223372036854775807, /)>

In [94]:
#this function helps users to count the number of a particular observation or value in a list

new_list.count(5)    

4

In [95]:
new_list.count(5)

4

In [96]:
#this helps us to append

new_list.append(11)
new_list

[1, 2, 3, 4, 5, 5, 5, 5, 6, 7, 8, 9, 10, 11]

In [97]:
#new_list.append([12, 13])

In [98]:
new_list

[1, 2, 3, 4, 5, 5, 5, 5, 6, 7, 8, 9, 10, 11]

In [99]:
new_list.extend([12, 13])

In [100]:
new_list

[1, 2, 3, 4, 5, 5, 5, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [101]:
new_list.clear([12, 13])

TypeError: clear() takes no arguments (1 given)

In [102]:
new_list.pop(-1)

13

In [103]:
new_list

[1, 2, 3, 4, 5, 5, 5, 5, 6, 7, 8, 9, 10, 11, 12]

In [104]:
new_list.sort()

In [105]:
new_list

[1, 2, 3, 4, 5, 5, 5, 5, 6, 7, 8, 9, 10, 11, 12]

In [107]:
new_list.insert(4, 50)

In [108]:
new_list

[1, 2, 3, 4, 50, 5, 5, 5, 5, 6, 7, 8, 9, 10, 11, 12]

In [110]:
import this 

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [111]:
#numpy meanms Numberical Python. Use for algebraec, array function and matrices operations
#Nupy changes codes to rows and columns called array
    

In [114]:
#this is a convention in python 

import numpy as np

In [115]:
new_list

[1, 2, 3, 4, 50, 5, 5, 5, 5, 6, 7, 8, 9, 10, 11, 12]

In [116]:
#the code below is used to form our list into array

new_list_array = np.array(new_list)

In [117]:
new_list_array

array([ 1,  2,  3,  4, 50,  5,  5,  5,  5,  6,  7,  8,  9, 10, 11, 12])

In [119]:
my_array= np.array([[1, 2, 3, 5], [3, 5, 9, 8], [7, 6, 3, 7]])
my_array

array([[1, 2, 3, 5],
       [3, 5, 9, 8],
       [7, 6, 3, 7]])

In [120]:
#the code below is used to check the shape of our array (my_array.shape)

my_array.shape

(3, 4)

In [121]:
new_list_array.shape

(16,)

In [128]:
#the codes below are used to check the row and column in our array
new_list_array[0]

1

In [134]:


my_array[:,0]



array([1, 3, 7])

In [135]:
my_array[:,1]


array([2, 5, 6])

In [136]:
my_array[:,2]

array([3, 9, 3])

In [137]:
my_array[0,:]

array([1, 2, 3, 5])

In [138]:
my_array[2, :]

array([7, 6, 3, 7])

In [151]:
my_array[1,2]

9

In [163]:
my_array[1,3]

8

In [167]:
my_array[2,3]

7

In [189]:
my_array[1:3,2:4]

array([[9, 8],
       [3, 7]])

In [196]:
self_array= np.array([[2, 4, 6, 8], [9, 3, 8, 7], [2, 5, 9, 8], [1, 6, 2, 3]])
self_array

array([[2, 4, 6, 8],
       [9, 3, 8, 7],
       [2, 5, 9, 8],
       [1, 6, 2, 3]])

In [197]:
self_array[1:3,2]

array([8, 9])

In [198]:
##Assignments
#Get all numpy method
#state breifly what they are used for and create one example from each

In [200]:
nupy

NameError: name 'nupy' is not defined

In [1]:
#6th December, 2019 Friday being 3rd AI Class       NUMPY CLASS

In [2]:
#For loop

import numpy as np


In [3]:
def minus(x,y):
    try:
        return x - y
    except TypeError:
        return float(x) - float(y)

In [4]:
minus(100,25)

75

In [5]:
def multiply(x,y,z):
    return x*y*z

In [6]:
multiply(10,2,5)

100

In [7]:
#Lambda function  this is a function can only be used once after declaration

add_mine = lambda x : x + 75
add_mine(26)

101

In [8]:
#for loop function (this code is used for iteration i.e. to look through a range of observations)

for x in range (3,9):
    print(x/3)

1.0
1.3333333333333333
1.6666666666666667
2.0
2.3333333333333335
2.6666666666666665


In [12]:
# round  is a function for "rounding up the values to the nearest whole number"

for x in range (3,9):
    print(round(x/3))

1
1
2
2
2
3


In [13]:
# The code below is used to DISPLAY the range of values in a specified observation

for x in range (3,9):

    print(x)

3
4
5
6
7
8


In [14]:
# The code below is used to PRINT or convert the output from float (Decimal) to intergeer (whole number). But please note that
#it will display the outcome without rounding up the values

for x in range (3,9):
    print(int(x/3))

1
1
1
2
2
2


In [16]:
for i in [3, 6, 9, 12, 15, 18, 21]:
    print (range(i))


range(0, 3)
range(0, 6)
range(0, 9)
range(0, 12)
range(0, 15)
range(0, 18)
range(0, 21)


# PANDAS TUTORIAL

In [17]:
#PANDAS   
#There are 2 types of PANDAS  (i) Pandas Series  (ii) Pandas Dataframe
# (i) Pandas Series refers to a set of data or observation with single list of column
#(ii) Pandas Dataframe refers observations having rows and column
#PANDAS is used to read in data or import dataset

#EXAMPLES below

#df.dtype to check data type

In [21]:
import pandas as pd

In [23]:
df = pd.read_csv('train_Practise.csv')

#The code below is used for checking the data type

#df.dtypes

ward                  object
total_households     float64
total_individuals    float64
target               float64
dw_00                float64
                      ...   
pw_08                  int64
ADM4_PCODE            object
lat                  float64
lon                  float64
NL                   float64
Length: 63, dtype: object

In [25]:
#The code below is used for checking the shape of the data e.g. how many rows and columns

df.shape

(2822, 63)

In [27]:
#The code is used to print the data or values from the 1st observation to the fifth as default 

#df.head()

ward  total_households  total_individuals     target     dw_00  \
0  41601001: Ward 1        1674.45058         5888.20750  16.773757  0.933841   
1  41601002: Ward 2        1736.99230         6735.33812  21.496661  0.696940   
2  41601003: Ward 3        2403.57591         7273.04995  10.931425  0.810545   
3  41601004: Ward 4        1740.78737         5734.49046  23.119257  0.659914   
4  41601005: Ward 5        1730.51451         6657.23835  13.652252  0.950575   

      dw_01     dw_02     dw_03     dw_04     dw_05  ...     pw_03     pw_04  \
0  0.000846  0.005490  0.000676  0.000000  0.001372  ...  0.002848  0.007537   
1  0.001253  0.004402  0.000000  0.002301  0.001323  ...  0.014566  0.057127   
2  0.004517  0.008891  0.003986  0.007735  0.000956  ...  0.057560  0.010358   
3  0.000000  0.006129  0.000000  0.000813  0.037245  ...  0.000000  0.000669   
4  0.000655  0.001473  0.000598  0.006999  0.000818  ...  0.004859  0.001290   

      pw_05     pw_06  pw_07  pw_08  ADM4_PCODE        lat        lon  \
0  0.000000  0.012928      0      0   ZA4161001 -29.682270  24.734743   
1  0.019092  0.004131      0      0   ZA4161002 -29.119311  24.757737   
2  0.001421  0.040881      0      0   ZA4161003 -29.142276  25.094093   
3  0.000000  0.005011      0      0   ZA4161004 -29.372052  24.942867   
4  0.000673  0.017629      0      0   ZA4161005 -29.409381  25.290165   

         NL  
0  0.292039  
1  3.207775  
2  0.000000  
3  2.038778  
4  0.000000  

[5 rows x 63 columns]

In [28]:
#The code below is used to print data from the 1st observation to the 20th observation.
#Note that u can input the size of observation you want to print inside the parenthesis

df.head(20)

ward  total_households  total_individuals     target  \
0   41601001: Ward 1        1674.45058         5888.20750  16.773757   
1   41601002: Ward 2        1736.99230         6735.33812  21.496661   
2   41601003: Ward 3        2403.57591         7273.04995  10.931425   
3   41601004: Ward 4        1740.78737         5734.49046  23.119257   
4   41601005: Ward 5        1730.51451         6657.23835  13.652252   
5   41601006: Ward 6        1956.16888         6340.05782  25.249880   
6   41602001: Ward 1        1966.40293         6230.77491  19.984585   
7   41602002: Ward 2        2214.44168         6873.93123  16.511081   
8   41602003: Ward 3        2022.95917         6736.49015  25.962117   
9   41602004: Ward 4        1775.53323         5682.10110  21.744166   
10  41602005: Ward 5        1869.05745         5738.19717  18.915248   
11  41602006: Ward 6        1935.43743         5729.28787  23.339213   
12  41602007: Ward 7        1878.04354         5719.76277  18.927365   
13  41602008: Ward 8        1981.27191         6459.97703  22.099416   
14  41603001: Ward 1        1704.17197         6181.22961  33.262138   
15  41603002: Ward 2        2207.67672         7370.30875  20.360682   
16  41603003: Ward 3        2035.76863         6307.33402  27.473530   
17  41603004: Ward 4        1000.49291         2981.50275  20.105452   
18  41603005: Ward 5        1552.08727         4762.15554  21.867528   
19  41603006: Ward 6        2292.33610         6543.25584  20.190361   

       dw_00     dw_01     dw_02     dw_03     dw_04     dw_05  ...     pw_03  \
0   0.933841  0.000846  0.005490  0.000676  0.000000  0.001372  ...  0.002848   
1   0.696940  0.001253  0.004402  0.000000  0.002301  0.001323  ...  0.014566   
2   0.810545  0.004517  0.008891  0.003986  0.007735  0.000956  ...  0.057560   
3   0.659914  0.000000  0.006129  0.000000  0.000813  0.037245  ...  0.000000   
4   0.950575  0.000655  0.001473  0.000598  0.006999  0.000818  ...  0.004859   
5   0.766832  0.000579  0.005874  0.000000  0.000000  0.001448  ...  0.020771   
6   0.908400  0.006857  0.002941  0.000576  0.000720  0.001905  ...  0.003827   
7   0.890079  0.004549  0.002262  0.001151  0.000512  0.001805  ...  0.006364   
8   0.912298  0.002799  0.003688  0.000560  0.001260  0.000560  ...  0.006109   
9   0.882665  0.005227  0.009128  0.000000  0.003687  0.002839  ...  0.002644   
10  0.946438  0.001970  0.000641  0.000000  0.000758  0.001247  ...  0.009061   
11  0.917469  0.001568  0.018096  0.001919  0.008440  0.000000  ...  0.000539   
12  0.859259  0.003670  0.003503  0.000620  0.000620  0.000000  ...  0.014980   
13  0.795118  0.002446  0.001303  0.000522  0.000000  0.001858  ...  0.001666   
14  0.636968  0.003175  0.002160  0.000000  0.000000  0.000831  ...  0.000000   
15  0.914012  0.002071  0.008279  0.000000  0.000000  0.007271  ...  0.006132   
16  0.823976  0.005446  0.005703  0.000508  0.000000  0.011471  ...  0.006617   
17  0.908061  0.001197  0.001132  0.001415  0.000000  0.025884  ...  0.001197   
18  0.858647  0.000751  0.017088  0.000000  0.000000  0.002330  ...  0.002855   
19  0.874696  0.021939  0.000508  0.000988  0.000508  0.011442  ...  0.004057   

       pw_04     pw_05     pw_06  pw_07  pw_08  ADM4_PCODE        lat  \
0   0.007537  0.000000  0.012928      0      0   ZA4161001 -29.682270   
1   0.057127  0.019092  0.004131      0      0   ZA4161002 -29.119311   
2   0.010358  0.001421  0.040881      0      0   ZA4161003 -29.142276   
3   0.000669  0.000000  0.005011      0      0   ZA4161004 -29.372052   
4   0.001290  0.000673  0.017629      0      0   ZA4161005 -29.409381   
5   0.002275  0.024184  0.039423      0      0   ZA4161006 -29.126870   
6   0.000509  0.002542  0.020192      0      0   ZA4162001 -29.640860   
7   0.001279  0.000526  0.025246      0      0   ZA4162002 -30.029163   
8   0.001276  0.000000  0.008791      0      0   ZA4162003 -30.462176   
9   0.000000  0.000583  0.002073      0      0   ZA4162004 -30.420421  

In [30]:
#The code is used to print the data or values from the last (5th) observation to the 1st as default

df.tail()

ward  total_households  total_individuals     target  \
2817  34503001: Ward 1        3261.68067        11551.56486   6.393480   
2818  34503002: Ward 2        1463.06432         7908.90411  15.668000   
2819  34503003: Ward 3        1395.18881         6242.37527  13.238795   
2820  34503004: Ward 4        1679.66964         8014.73089  17.639523   
2821  34503005: Ward 5        3008.38687         7899.36498  12.457680   

         dw_00     dw_01     dw_02     dw_03     dw_04     dw_05  ...  \
2817  0.874972  0.003146  0.017230  0.004735  0.048888  0.000654  ...   
2818  0.636235  0.002262  0.010433  0.000000  0.003030  0.000000  ...   
2819  0.855975  0.006601  0.061118  0.000812  0.003912  0.000812  ...   
2820  0.792552  0.004423  0.016099  0.000000  0.000674  0.000000  ...   
2821  0.254215  0.003310  0.121954  0.000000  0.001770  0.001023  ...   

         pw_03     pw_04     pw_05     pw_06  pw_07  pw_08  ADM4_PCODE  \
2817  0.000472  0.000472  0.000000  0.006203      0      0   ZA3453001   
2818  0.003030  0.000713  0.000000  0.008414      0      0   ZA3453002   
2819  0.002150  0.001458  0.000000  0.003670      0      0   ZA3453003   
2820  0.009235  0.007870  0.000000  0.004803      0      0   ZA3453004   
2821  0.003107  0.001636  0.000332  0.001770      0      0   ZA3453005   

            lat        lon        NL  
2817 -27.675590  23.057920  9.118927  
2818 -27.591408  22.907161  1.697395  
2819 -27.952550  22.749698  2.792501  
2820 -27.913875  22.755314  2.793699  
2821 -27.741804  22.856933  0.001200  

[5 rows x 63 columns]

In [31]:
#This is used to print the observations from the tail (end) in this case 20th observation to the 1st observation

#df.tail(20)

ward  total_households  total_individuals     target  \
2802  34501014: Ward 14        1403.31972         5181.55434  34.092909   
2803  34501015: Ward 15        1413.31960         5945.02570  29.202312   
2804   34502001: Ward 1        1667.75905         6121.10372   5.443823   
2805   34502002: Ward 2        2676.90014         8751.40681  21.315342   
2806   34502003: Ward 3        3495.97358         9996.25986  20.457931   
2807   34502004: Ward 4        1635.03317         5824.21418  24.327679   
2808   34502005: Ward 5        1006.33326         3292.02866  29.062083   
2809   34502006: Ward 6        2895.80664         8819.14348  21.859571   
2810   34502007: Ward 7        1588.02370         5818.82566  32.908719   
2811   34502008: Ward 8        1794.27941         5990.58572  29.413963   
2812   34502009: Ward 9         964.17366         3784.03630  30.593096   
2813  34502010: Ward 10        2915.45302        11176.02950  26.177120   
2814  34502011: Ward 11        1906.32047         6932.78429  21.439577   
2815  34502012: Ward 12        2797.24959        10294.11620  29.065233   
2816  34502013: Ward 13        1472.32727         6850.95588  15.288742   
2817   34503001: Ward 1        3261.68067        11551.56486   6.393480   
2818   34503002: Ward 2        1463.06432         7908.90411  15.668000   
2819   34503003: Ward 3        1395.18881         6242.37527  13.238795   
2820   34503004: Ward 4        1679.66964         8014.73089  17.639523   
2821   34503005: Ward 5        3008.38687         7899.36498  12.457680   

         dw_00     dw_01     dw_02     dw_03     dw_04     dw_05  ...  \
2802  0.638103  0.264137  0.006326  0.000767  0.000000  0.000000  ...   
2803  0.695525  0.247025  0.002201  0.003232  0.000000  0.000724  ...   
2804  0.874628  0.004918  0.053078  0.012121  0.022158  0.004643  ...   
2805  0.608211  0.015249  0.003865  0.000402  0.000386  0.000467  ...   
2806  0.861800  0.008963  0.007983  0.001176  0.000357  0.000308  ...   
2807  0.780476  0.036561  0.009167  0.022083  0.000000  0.000000  ...   
2808  0.910403  0.018752  0.003057  0.000000  0.000000  0.000000  ...   
2809  0.777909  0.061685  0.014811  0.000729  0.000432  0.000903  ...   
2810  0.611485  0.338007  0.001329  0.000000  0.000000  0.000000  ...   
2811  0.821450  0.092236  0.000600  0.002010  0.000000  0.000000  ...   
2812  0.702412  0.133519  0.002711  0.002122  0.000000  0.000000  ...   
2813  0.819065  0.082802  0.005098  0.000355  0.000369  0.000000  ...   
2814  0.831636  0.023670  0.006449  0.017388  0.000000  0.002779  ...   
2815  0.774917  0.081462  0.003547  0.000731  0.000447  0.001505  ...   
2816  0.766408  0.084505  0.008503  0.000703  0.000849  0.052410  ...   
2817  0.874972  0.003146  0.017230  0.004735  0.048888  0.000654  ...   
2818  0.636235  0.002262  0.010433  0.000000  0.003030  0.000000  ...   
2819  0.855975  0.006601  0.061118  0.000812  0.003912  0.000812  ...   
2820  0.792552  0.004423  0.016099  0.000000  0.000674  0.000000  ...   
2821  0.254215  0.003310  0.121954  0.000000  0.001770  0.001023  ...   

         pw_03     pw_04     pw_05     pw_06  pw_07  pw_08  ADM4_PCODE  \
2802  0.087215  0.031572  0.165774  0.162274      0      0   ZA3451014   
2803  0.248160  0.051521  0.020029  0.047262      0      0   ZA3451015   
2804  0.000679  0.002121  0.000679  0.010975      0      0   ZA3452001   
2805  0.031824  0.078990  0.028800  0.032213      0      0   ZA3452002   
2806  0.086404  0.035525  0.017409  0.017095      0      0   ZA3452003   
2807  0.090955  0.021277  0.053220  0.001573      0      0   ZA3452004   
2808  0.192747  0.057960  0.011649  0.002598      0      0   ZA3452005   
2809  0.210006  0.126698  0.063994  0.005194      0      0   ZA3452006   
2810  0.222549  0.148511  0.041287  0.007937      0      0   ZA3452007   
2811  0.108112  0.032096  0.000696  0.007089      0      0   ZA3452008   
2812  0.183343  0.079679  0.051607  0.007202      0      0   ZA3452009   
2813  0.204246  0.068

In [33]:
# The code below is used to print the list of heads or column heads in the dataset

df.columns

Index(['ward', 'total_households', 'total_individuals', 'target', 'dw_00',
       'dw_01', 'dw_02', 'dw_03', 'dw_04', 'dw_05', 'dw_06', 'dw_07', 'dw_08',
       'dw_09', 'dw_10', 'dw_11', 'dw_12', 'dw_13', 'psa_00', 'psa_01',
       'psa_02', 'psa_03', 'psa_04', 'stv_00', 'stv_01', 'car_00', 'car_01',
       'lln_00', 'lln_01', 'lan_00', 'lan_01', 'lan_02', 'lan_03', 'lan_04',
       'lan_05', 'lan_06', 'lan_07', 'lan_08', 'lan_09', 'lan_10', 'lan_11',
       'lan_12', 'lan_13', 'lan_14', 'pg_00', 'pg_01', 'pg_02', 'pg_03',
       'pg_04', 'lgt_00', 'pw_00', 'pw_01', 'pw_02', 'pw_03', 'pw_04', 'pw_05',
       'pw_06', 'pw_07', 'pw_08', 'ADM4_PCODE', 'lat', 'lon', 'NL'],
      dtype='object')

In [35]:
# The code below is used to display the list of dataset if there are missing values or not, data type e.g float, integer etc

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2822 entries, 0 to 2821
Data columns (total 63 columns):
ward                 2822 non-null object
total_households     2822 non-null float64
total_individuals    2822 non-null float64
target               2822 non-null float64
dw_00                2822 non-null float64
dw_01                2822 non-null float64
dw_02                2822 non-null float64
dw_03                2822 non-null float64
dw_04                2822 non-null float64
dw_05                2822 non-null float64
dw_06                2822 non-null float64
dw_07                2822 non-null float64
dw_08                2822 non-null float64
dw_09                2822 non-null float64
dw_10                2822 non-null float64
dw_11                2822 non-null float64
dw_12                2822 non-null int64
dw_13                2822 non-null int64
psa_00               2822 non-null float64
psa_01               2822 non-null float64
psa_02               2822 non-null flo

In [36]:
# The code below is used to print the SAMPLE OF THE WHOLE  dataset. but default is 1 sample (i.e. no value inside the bracket below)

df.sample()

ward  total_households  total_individuals     target  \
2086  83102004: Ward 4        2877.88124        10112.94113  19.988166   

         dw_00     dw_01     dw_02  dw_03     dw_04     dw_05  ...     pw_03  \
2086  0.757257  0.002585  0.001503    0.0  0.000828  0.000897  ...  0.006053   

         pw_04    pw_05     pw_06  pw_07  pw_08  ADM4_PCODE        lat  \
2086  0.003692  0.00076  0.013284      0      0   ZA8312004 -25.848925   

            lon         NL  
2086  29.124926  32.246137  

[1 rows x 63 columns]

In [37]:
# The code below is used to print 20 SAMPLE OF THE WHOLE  dataset. but default is 1 sample (i.e.  value 20 inside the bracket below)

df.sample(20)

ward  total_households  total_individuals     target  \
96      41901007: Ward 7        2348.32625         7130.76547  30.165754   
1899   94702014: Ward 14        3821.27850        12942.95027  23.528938   
2496   63803030: Ward 30        3453.88951         8842.25240  30.896553   
1491  59500101: Ward 101        9936.30020        25459.60705  21.994916   
1172    52405002: Ward 2        2136.35070         9886.62612  39.028982   
1692   93404028: Ward 28        4453.73444        15854.22046  30.268280   
1398    59500008: Ward 8       10166.48598        35539.33710  14.507857   
607    79800066: Ward 66       13998.59911        45451.44616  11.817546   
2403    63704003: Ward 3        1425.10650         4907.86641  11.047106   
2655    30602006: Ward 6        1666.71059         6111.28938  18.792936   
2639    64004005: Ward 5        1629.56619         6172.19051   7.507126   
18      41603005: Ward 5        1552.08727         4762.15554  21.867528   
1939   94703024: Ward 24        1936.04524         7873.71186  44.965685   
23      41801004: Ward 4        1403.67421         4410.22134  24.995485   
962     52702003: Ward 3        1568.78461         9421.71530  36.867199   
2207   83106022: Ward 22        2454.68446         9544.20883  35.665886   
2783    30904004: Ward 4        1955.92999         5866.52196  19.581259   
147    41904012: Ward 12        3748.70651        12846.17839  34.951030   
2311   63701011: Ward 11        1826.11794         7135.03893  22.594950   
1800   93505025: Ward 25        1850.38872         8079.17669  41.722929   

         dw_00     dw_01     dw_02     dw_03     dw_04     dw_05  ...  \
96    0.781502  0.000000  0.000979  0.000000  0.000000  0.000000  ...   
1899  0.783418  0.017059  0.007953  0.001347  0.001106  0.000000  ...   
2496  0.703579  0.003317  0.003370  0.000000  0.000000  0.000000  ...   
1491  0.371810  0.005694  0.105825  0.025120  0.013640  0.005938  ...   
1172  0.550683  0.377221  0.034156  0.000983  0.000479  0.000504  ...   
1692  0.869872  0.048671  0.000760  0.002126  0.000465  0.019240  ...   
1398  0.632885  0.189572  0.015118  0.068510  0.041933  0.004194  ...   
607   0.575422  0.005299  0.223457  0.005991  0.007528  0.019264  ...   
2403  0.815827  0.001994  0.022284  0.005706  0.003343  0.002887  ...   
2655  0.947306  0.017168  0.004391  0.000000  0.000000  0.000000  ...   
2639  0.812183  0.012444  0.014343  0.002245  0.006365  0.004472  ...   
18    0.858647  0.000751  0.017088  0.000000  0.000000  0.002330  ...   
1939  0.917854  0.051600  0.003596  0.000000  0.000000  0.000000  ...   
23    0.807399  0.004555  0.012579  0.000807  0.001009  0.003319  ...   
962   0.751400  0.205356  0.021296  0.001147  0.000686  0.000000  ...   
2207  0.906539  0.006287  0.002609  0.000000  0.000855  0.000000  ...   
2783  0.950279  0.005264  0.004538  0.001341  0.000000  0.003197  ...   
147   0.738639  0.140333  0.000378  0.001905  0.000000  0.005788  ...   
2311  0.783972  0.011406  0.003507  0.002957  0.000000  0.003547  ...   
1800  0.977141  0.012074  0.001873  0.000000  0.000000  0.000630  ...   

         pw_03     pw_04     pw_05     pw_06  pw_07  pw_08  ADM4_PCODE  \
96    0.026448  0.007331  0.000000  0.003655      0      0   ZA4191007   
1899  0.155521  0.046881  0.004597  0.110873      0      0   ZA9472014   
2496  0.013967  0.002787  0.005407  0.323423      0      0   ZA6383030   
1491  0.122495  0.010859  0.000825  0.030358      0      0   ZA5950101   
1172  0.164483  0.056684  0.081389  0.441240      0      0   ZA5245002   
1692  0.070430  0.090599  0.013602  0.196315      0      0   ZA9344028   
1398  0.004364  0.002744  0.001576  0.039658      0      0   ZA5950008   
607   0.001422  0.000454  0.000246  0.005900      0      0   ZA7980066   
2403  0.005636  0.003631  0.001163  0.024760      0      0   ZA6374003   
2655  0.001921  0.000680  0.000000  0.016113      0      0   ZA3062006   
2639  0.034619  0.000972  0.001432  0.013892      0      0   ZA6404005   
1

In [38]:
df.head()

ward  total_households  total_individuals     target     dw_00  \
0  41601001: Ward 1        1674.45058         5888.20750  16.773757  0.933841   
1  41601002: Ward 2        1736.99230         6735.33812  21.496661  0.696940   
2  41601003: Ward 3        2403.57591         7273.04995  10.931425  0.810545   
3  41601004: Ward 4        1740.78737         5734.49046  23.119257  0.659914   
4  41601005: Ward 5        1730.51451         6657.23835  13.652252  0.950575   

      dw_01     dw_02     dw_03     dw_04     dw_05  ...     pw_03     pw_04  \
0  0.000846  0.005490  0.000676  0.000000  0.001372  ...  0.002848  0.007537   
1  0.001253  0.004402  0.000000  0.002301  0.001323  ...  0.014566  0.057127   
2  0.004517  0.008891  0.003986  0.007735  0.000956  ...  0.057560  0.010358   
3  0.000000  0.006129  0.000000  0.000813  0.037245  ...  0.000000  0.000669   
4  0.000655  0.001473  0.000598  0.006999  0.000818  ...  0.004859  0.001290   

      pw_05     pw_06  pw_07  pw_08  ADM4_PCODE        lat        lon  \
0  0.000000  0.012928      0      0   ZA4161001 -29.682270  24.734743   
1  0.019092  0.004131      0      0   ZA4161002 -29.119311  24.757737   
2  0.001421  0.040881      0      0   ZA4161003 -29.142276  25.094093   
3  0.000000  0.005011      0      0   ZA4161004 -29.372052  24.942867   
4  0.000673  0.017629      0      0   ZA4161005 -29.409381  25.290165   

         NL  
0  0.292039  
1  3.207775  
2  0.000000  
3  2.038778  
4  0.000000  

[5 rows x 63 columns]

In [39]:
# The code below is used to print the # SAMPLE DESCRIPTION OF THE WHOLE  dataset. I.E. DESCRIPTIVE STATISTICS OF THE DATASET

The df.describe()

total_households  total_individuals       target        dw_00  \
count       2822.000000        2822.000000  2822.000000  2822.000000   
mean        3665.281214       12869.130053    24.507554     0.712196   
std         3266.364522        9696.690518    10.294387     0.214035   
min            1.000000         402.000000     0.000000     0.000000   
25%         1778.858235        7071.205695    16.751556     0.594212   
50%         2398.249935        9366.989680    24.156670     0.766841   
75%         3987.080563       14241.233015    32.226553     0.881708   
max        39684.942130       91716.746370    55.528423     0.994962   

             dw_01        dw_02        dw_03        dw_04        dw_05  \
count  2822.000000  2822.000000  2822.000000  2822.000000  2822.000000   
mean      0.092616     0.032043     0.006057     0.008665     0.006289   
std       0.182852     0.080253     0.019374     0.030697     0.024606   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.002895     0.002407     0.000000     0.000000     0.000000   
50%       0.010425     0.005762     0.000807     0.000607     0.000865   
75%       0.068209     0.027913     0.002538     0.002225     0.003027   
max       0.931490     0.951806     0.264239     0.392085     0.435912   

             dw_06  ...        pw_02        pw_03        pw_04        pw_05  \
count  2822.000000  ...  2822.000000  2822.000000  2822.000000  2822.000000   
mean      0.022375  ...     0.127555     0.041589     0.019655     0.011008   
std       0.037127  ...     0.156400     0.057331     0.032926     0.023672   
min       0.000000  ...     0.000000     0.000000     0.000000     0.000000   
25%       0.002716  ...     0.008673     0.002099     0.000715     0.000159   
50%       0.008639  ...     0.069065     0.016496     0.005164     0.001459   
75%       0.025218  ...     0.183384     0.058626     0.025055     0.009432   
max       0.412936  ...     1.000000     0.327393     0.306787     0.228261   

             pw_06   pw_07   pw_08          lat          lon           NL  
count  2822.000000  2822.0  2822.0  2822.000000  2822.000000  2822.000000  
mean      0.110818     0.0     0.0   -26.880740    28.666515    17.437560  
std       0.185401     0.0     0.0     2.021279     2.373809    18.958621  
min       0.000000     0.0     0.0   -32.490089    16.760022     0.000000  
25%       0.005217     0.0     0.0   -28.569019    27.707932     3.033397  
50%       0.025165     0.0     0.0   -26.549866    28.959679     9.205572  
75%       0.116638     0.0     0.0   -25.572130    30.441505    26.890531  
max       0.961523     0.0     0.0   -22.331267    32.858249    63.000000  

[8 rows x 61 columns]

In [40]:
#The code below is used to find CORRELATION IN THE DATASET

df.corr()

total_households  total_individuals    target     dw_00  \
total_households           1.000000           0.959244 -0.374833 -0.226119   
total_individuals          0.959244           1.000000 -0.293827 -0.200350   
target                    -0.374833          -0.293827  1.000000  0.018461   
dw_00                     -0.226119          -0.200350  0.018461  1.000000   
dw_01                     -0.231304          -0.161183  0.458206 -0.614702   
...                             ...                ...       ...       ...   
pw_07                           NaN                NaN       NaN       NaN   
pw_08                           NaN                NaN       NaN       NaN   
lat                        0.063018           0.039653  0.120381  0.348089   
lon                        0.032249           0.104198  0.347088 -0.152692   
NL                         0.708701           0.684853 -0.514398 -0.133895   

                      dw_01     dw_02     dw_03     dw_04     dw_05     dw_06  \
total_households  -0.231304  0.222825  0.328743  0.314811  0.095374  0.284317   
total_individuals -0.161183  0.178921  0.255194  0.245253  0.109852  0.252280   
target             0.458206 -0.232727 -0.338137 -0.385533 -0.146357 -0.248573   
dw_00             -0.614702 -0.356335 -0.154956 -0.126421 -0.076181 -0.181262   
dw_01              1.000000  0.000617 -0.075112 -0.112250 -0.095776 -0.099431   
...                     ...       ...       ...       ...       ...       ...   
pw_07                   NaN       NaN       NaN       NaN       NaN       NaN   
pw_08                   NaN       NaN       NaN       NaN       NaN       NaN   
lat               -0.346198 -0.126910 -0.042252  0.009724 -0.093791  0.015586   
lon                0.349469  0.075945  0.028536 -0.028597 -0.135910 -0.052148   
NL                -0.338058  0.304287  0.321311  0.356428  0.180807  0.403524   

                   ...     pw_02     pw_03     pw_04     pw_05     pw_06  \
total_households   ... -0.140827 -0.149199 -0.121961 -0.110339 -0.228412   
total_individuals  ... -0.127982 -0.135562 -0.103966 -0.084651 -0.174518   
target             ...  0.442441  0.440941  0.389467  0.349653  0.470676   
dw_00              ... -0.064290 -0.079610 -0.059986 -0.038534 -0.297510   
dw_01              ...  0.222130  0.250931  0.202204  0.211378  0.600377   
...                ...       ...       ...       ...       ...       ...   
pw_07              ...       NaN       NaN       NaN       NaN       NaN   
pw_08              ...       NaN       NaN       NaN       NaN       NaN   
lat                ...  0.069398  0.114066  0.150117  0.114295 -0.029484   
lon                ...  0.077424  0.075826  0.136322  0.165803  0.325206   
NL                 ... -0.312929 -0.316221 -0.254358 -0.212811 -0.341468   

                   pw_07  pw_08       lat       lon        NL  
total_households     NaN    NaN  0.063018  0.032249  0.708701  
total_individuals    NaN    NaN  0.039653  0.104198  0.684853  
target               NaN    NaN  0.120381  0.347088 -0.514398  
dw_00                NaN    NaN  0.348089 -0.152692 -0.133895  
dw_01                NaN    NaN -0.346198  0.349469 -0.338058  
...                  ...    ...       ...       ...       ...  
pw_07                NaN    NaN       NaN       NaN       NaN  
pw_08                NaN    NaN       NaN       NaN       NaN  
lat                  NaN    NaN  1.000000  0.081587  0.049429  
lon                  NaN    NaN  0.081587  1.000000 -0.026927  
NL                   NaN    NaN  0.049429 -0.026927  1.000000  

[61 rows x 61 columns]

In [43]:
df['ward'].value_counts()

83102034: Ward 34    1
79900073: Ward 73    1
52702012: Ward 12    1
30903001: Ward 1     1
52705013: Ward 13    1
                    ..
79700023: Ward 23    1
30901026: Ward 26    1
52804023: Ward 23    1
83005002: Ward 2     1
52102010: Ward 10    1
Name: ward, Length: 2822, dtype: int64

In [44]:
df.ward

0       41601001: Ward 1
1       41601002: Ward 2
2       41601003: Ward 3
3       41601004: Ward 4
4       41601005: Ward 5
              ...       
2817    34503001: Ward 1
2818    34503002: Ward 2
2819    34503003: Ward 3
2820    34503004: Ward 4
2821    34503005: Ward 5
Name: ward, Length: 2822, dtype: object

In [45]:
type(df.ward)

pandas.core.series.Series

In [46]:
type(df)

pandas.core.frame.DataFrame

In [49]:
df['total_households'].value_counts()

7068.04709     1
1951.79282     1
1556.93774     1
2086.09070     1
5698.44972     1
              ..
2019.63474     1
9577.94399     1
12280.92254    1
4369.07002     1
178.00000      1
Name: total_households, Length: 2822, dtype: int64

In [51]:
df.mode()

ward  total_households  total_individuals     target  \
0      30601001: Ward 1           1.00000          402.00000   0.000000   
1      30601002: Ward 2         178.00000          896.02641   1.671886   
2      30601003: Ward 3         244.30116         1266.29666   2.672209   
3      30601004: Ward 4         440.90597         1586.70575   3.234013   
4      30602001: Ward 1         511.53265         1734.05250   3.237956   
...                 ...               ...                ...        ...   
2817  94703027: Ward 27       22805.57563        59086.15228  52.010403   
2818  94703028: Ward 28       22986.82397        62240.87246  52.171511   
2819  94703029: Ward 29       23544.17746        63287.85852  52.248392   
2820  94703030: Ward 30       28935.65396        84536.12012  52.601169   
2821  94703031: Ward 31       39684.94213        91716.74637  55.528423   

         dw_00  dw_01  dw_02  dw_03  dw_04  dw_05  ...  pw_03  pw_04  pw_05  \
0     0.000000    0.0    0.0    0.0    0.0    0.0  ...    0.0    0.0    0.0   
1     0.005552    NaN    NaN    NaN    NaN    NaN  ...    NaN    NaN    NaN   
2     0.021379    NaN    NaN    NaN    NaN    NaN  ...    NaN    NaN    NaN   
3     0.021926    NaN    NaN    NaN    NaN    NaN  ...    NaN    NaN    NaN   
4     0.035003    NaN    NaN    NaN    NaN    NaN  ...    NaN    NaN    NaN   
...        ...    ...    ...    ...    ...    ...  ...    ...    ...    ...   
2817  0.988630    NaN    NaN    NaN    NaN    NaN  ...    NaN    NaN    NaN   
2818  0.989022    NaN    NaN    NaN    NaN    NaN  ...    NaN    NaN    NaN   
2819  0.989259    NaN    NaN    NaN    NaN    NaN  ...    NaN    NaN    NaN   
2820  0.989374    NaN    NaN    NaN    NaN    NaN  ...    NaN    NaN    NaN   
2821  0.994962    NaN    NaN    NaN    NaN    NaN  ...    NaN    NaN    NaN   

      pw_06  pw_07  pw_08  ADM4_PCODE        lat        lon   NL  
0       0.0    0.0    0.0   ZA3061001 -32.490089  16.760022  0.0  
1       NaN    NaN    NaN   ZA3061002 -31.888645  17.002219  NaN  
2       NaN    NaN    NaN   ZA3061003 -31.814231  17.132129  NaN  
3       NaN    NaN    NaN   ZA3061004 -31.665732  17.264832  NaN  
4       NaN    NaN    NaN   ZA3062001 -31.469394  17.299090  NaN  
...     ...    ...    ...         ...        ...        ...  ...  
2817    NaN    NaN    NaN   ZA9473027 -22.405593  32.715017  NaN  
2818    NaN    NaN    NaN   ZA9473028 -22.382846  32.736878  NaN  
2819    NaN    NaN    NaN   ZA9473029 -22.340825  32.757426  NaN  
2820    NaN    NaN    NaN   ZA9473030 -22.337394  32.820105  NaN  
2821    NaN    NaN    NaN   ZA9473031 -22.331267  32.858249  NaN  

[2822 rows x 63 columns]

In [54]:
df.pg_00.mean()

0.8621424599109138

In [55]:
#find MISSING VALUE

df.pg_00.isnull()

0       False
1       False
2       False
3       False
4       False
        ...  
2817    False
2818    False
2819    False
2820    False
2821    False
Name: pg_00, Length: 2822, dtype: bool

In [59]:
df.skew()

total_households     2.715798
total_individuals    2.164591
target               0.109293
dw_00               -1.027741
dw_01                2.537747
                       ...   
pw_07                0.000000
pw_08                0.000000
lat                 -0.024309
lon                 -1.256801
NL                   1.149866
Length: 61, dtype: float64

In [58]:
df.kurtosis()

total_households     11.665419
total_individuals     5.843852
target               -0.698781
dw_00                 0.430059
dw_01                 5.765620
                       ...    
pw_07                 0.000000
pw_08                 0.000000
lat                  -0.740603
lon                   2.770354
NL                    0.067994
Length: 61, dtype: float64

In [62]:
pd.crosstab(df.ward, df.lat)

lat                -32.490089  -31.888645  -31.814231  -31.665732  -31.469394  \
ward                                                                            
30601001: Ward 1            0           0           0           0           0   
30601002: Ward 2            0           0           0           0           0   
30601003: Ward 3            0           0           0           0           0   
30601004: Ward 4            0           0           0           0           0   
30602001: Ward 1            0           0           0           0           0   
...                       ...         ...         ...         ...         ...   
94703027: Ward 27           0           0           0           0           0   
94703028: Ward 28           0           0           0           0           0   
94703029: Ward 29           0           0           0           0           0   
94703030: Ward 30           0           0           0           0           0   
94703031: Ward 31           0           0           0           0           0   

lat                -31.438364  -31.416559  -31.414525  -31.412418  -31.354671  \
ward                                                                            
30601001: Ward 1            0           0           0           0           0   
30601002: Ward 2            0           0           0           0           0   
30601003: Ward 3            0           0           0           0           0   
30601004: Ward 4            0           0           0           0           0   
30602001: Ward 1            0           0           0           0           0   
...                       ...         ...         ...         ...         ...   
94703027: Ward 27           0           0           0           0           0   
94703028: Ward 28           0           0           0           0           0   
94703029: Ward 29           0           0           0           0           0   
94703030: Ward 30           0           0           0           0           0   
94703031: Ward 31           0           0           0           0           0   

lat                ...  -22.713167  -22.708496  -22.672229  -22.605472  \
ward               ...                                                   
30601001: Ward 1   ...           0           0           0           0   
30601002: Ward 2   ...           0           0           0           0   
30601003: Ward 3   ...           0           0           0           0   
30601004: Ward 4   ...           0           0           0           0   
30602001: Ward 1   ...           0           0           0           0   
...                ...         ...         ...         ...         ...   
94703027: Ward 27  ...           0           0           0           0   
94703028: Ward 28  ...           0           0           0           0   
94703029: Ward 29  ...           0           0           0           0   
94703030: Ward 30  ...           0           0           0           0   
94703031: Ward 31  ...           0           0           0           0   

lat                -22.499977  -22.405593  -22.382846  -22.340825  -22.337394  \
ward                                                                            
30601001: Ward 1            0           0           0           0           0   
30601002: Ward 2            0           0           0           0           0   
30601003: Ward 3            0           0           0           0           0   
30601004: Ward 4            0           0           0           0           0   
30602001: Ward 1            0           0           0           0           0   
...                       ...         ...         ...         ...         ...   
94703027: Ward 27           0           0           0           0           0   
94703028: Ward 28           0           0           0           0           0   
94703029: Ward 29           0           0           0           0           0   
94703030: Ward 30           0         

# DATAFRAME TUTORIAL

In [64]:
dff = pd.DataFrame({'A': [11, 21, 31],
                   'B': [12, 22, 32],
                   'c': [11, 18, 16]})

# DROP TUTORIAL


In [66]:
##Axis means the X and Y axis with x =0 while Y axis = 1   pls see the code below

df.drop(['lat', 'lon'], axis = 1, inplace = True)

In [67]:
df.drop('ADM4_PCODE', axis = 1, inplace = True)

In [68]:
df.columns

Index(['ward', 'total_households', 'total_individuals', 'target', 'dw_00',
       'dw_01', 'dw_02', 'dw_03', 'dw_04', 'dw_05', 'dw_06', 'dw_07', 'dw_08',
       'dw_09', 'dw_10', 'dw_11', 'dw_12', 'dw_13', 'psa_00', 'psa_01',
       'psa_02', 'psa_03', 'psa_04', 'stv_00', 'stv_01', 'car_00', 'car_01',
       'lln_00', 'lln_01', 'lan_00', 'lan_01', 'lan_02', 'lan_03', 'lan_04',
       'lan_05', 'lan_06', 'lan_07', 'lan_08', 'lan_09', 'lan_10', 'lan_11',
       'lan_12', 'lan_13', 'lan_14', 'pg_00', 'pg_01', 'pg_02', 'pg_03',
       'pg_04', 'lgt_00', 'pw_00', 'pw_01', 'pw_02', 'pw_03', 'pw_04', 'pw_05',
       'pw_06', 'pw_07', 'pw_08', 'NL'],
      dtype='object')

# 12th December, 2019       PANDAS CLASS CONTINUATION

## Assignments
### Get all PANDAS method OR OPERATIONS
### State breifly what they are used for and create one example from each

# ===============================================================

# Creating Github and other Community accounts

In [2]:
# Downloade VS Code     or gitbash   on google.com 
#The VS Code is used to upload our code to the www.GITHUB.COM account and we make it private
#press CTRL + backtick  key on the keyboard (backtick key is the key under the ESC key, beside 1) is shortcut to VS notepad