# NUMPY DOCUMENTATION ASSIGNMENT

In [1]:
## nd.array means "Non Dimensional of arrays to be declared in a code"


In [5]:
#Arithmetic Operations

a=10 
b=20
d=18

In [6]:
c=(a*d)+b
c

200

In [9]:

f=d/b
f

0.9

In [10]:
#ndarray.ndim the number of axes (dimensions) of the array. 
#ndarray.shape the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). 
#The length of the shape tuple is therefore the number of axes, ndim. 
#ndarray.size the total number of elements of the array
#ndarray.dtype an object describing the type of the elements in the array
#ndarray.itemsize the size in bytes of each element of the array
#ndarray.data the buffer containing the actual elements of the array. 


# Example

In [14]:
import numpy as np 
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [16]:
a.shape
(3, 5)
a.ndim

2

In [18]:
a.dtype.name

'int32'

In [19]:
# Array creation in the numpy methods

a = np.array([1, 2, 3, 6, 8])   
a

#please note that:
                        #  a = np.array(1, 2, 3, 6, 8)  is WRONG
                        #  a = np.array([1, 2, 3, 6, 8])   is the correct code

array([1, 2, 3, 6, 8])

In [23]:
a.dtype                  #please note that dtype refers to data type. Either Integer or Float

dtype('int32')

In [24]:
b = np.array([0.6, 5.8, 7.2, 9.6])
b

array([0.6, 5.8, 7.2, 9.6])

In [25]:
b.dtype                    #In this case the DATATYPE return an output as FLOAT because the data are decimals

dtype('float64')

In [29]:
# Array transforms SEQUENCES OF SEQUENCES INTO 2-DIMENSIONAL SEQUENCES OF SEQUENCES. Pls see an Example below

b = np.array([(2.2, 8, 9, 12), (1, 3.8, 4, 7)])
b

array([[ 2.2,  8. ,  9. , 12. ],
       [ 1. ,  3.8,  4. ,  7. ]])

In [31]:
# The type of the array can also be explicitly specified at creation time

d = np.array ([(3, 8, 9), (5, 8, 10), (2, 9, 7)], dtype=complex)
d

array([[ 3.+0.j,  8.+0.j,  9.+0.j],
       [ 5.+0.j,  8.+0.j, 10.+0.j],
       [ 2.+0.j,  9.+0.j,  7.+0.j]])

In [33]:
# The function zeros creates an array full of zeros

np.zeros((3, 2), dtype=float)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [35]:
# The function zeros creates an array full of ones

np.ones((3,3), dtype=float)         #NOte that we can do the same datatype (dtype) for integer


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.empty((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [50]:
# The function can arrange values

a=np.arange (80)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79]


In [52]:
a=np.arange(80).reshape (10,8)    #This code helps to rearrange observations into arrat of specified rows and columns
print(a)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]
 [64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79]]


In [53]:
print(np.arange(80000))  #If an array is too large to be printed, NumPy automatically skips the central part of the array 
                          #and only prints the corners:


[    0     1     2 ... 79997 79998 79999]


## Printing Arrays in Numpy Implementation


In [1]:
##When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout: #
#• the last axis is printed from left to right,
#• the second-to-last is printed from top to bottom, 
#• the rest are also printed from top to bottom, with each slice separated from the next by an empty line. 
#One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.


In [12]:
#Example Given
import numpy as np
a=np.arange(100).reshape(10,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [13]:
#Similarly 

b=np.arange(15)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [15]:
#Reshaping the array into 3 X 5 matrix then we have the code below

b=np.arange(15).reshape(3,5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [25]:
## Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

import numpy as np

d = np.array([12, 16, 24, 28, 36])
e = np.arange(5)
e.array([0, 1, 2 ,3, 4])
f = d-e
print(f)

AttributeError: 'numpy.ndarray' object has no attribute 'array'

## Matrix Operations

In [26]:
##Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. 
##The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:

# Note that block letters are used for Matrix


In [47]:

A = np.array ([[3, 5, 2, 6],
               [6, 7, 3, 5]])

B = np.array ([[5, 2, 7, 3],
               [6, 2, 9, 3]])


In [44]:
A * B

array([[15, 10, 14, 18],
       [36, 14, 27, 15]])

In [49]:
A + B

array([[ 8,  7,  9,  9],
       [12,  9, 12,  8]])

In [50]:
A - B

array([[-2,  3, -5,  3],
       [ 0,  5, -6,  2]])

In [51]:
A**B

array([[  243,    25,   128,   216],
       [46656,    49, 19683,   125]], dtype=int32)

In [52]:
A / B

array([[0.6       , 2.5       , 0.28571429, 2.        ],
       [1.        , 3.5       , 0.33333333, 1.66666667]])

In [54]:
D = (A+B) - (A-B)

print(D)

[[10  4 14  6]
 [12  4 18  6]]


## Universal Functions 


### These are Mathematical Functions like: Sin, Cos, Tan, Expon etc Usually code as (ufunct)

In [56]:
G = np.arange(5)
G

array([0, 1, 2, 3, 4])

In [58]:
np.exp(G)        #used to find exponential function of Variable G

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [59]:
np.sqrt(G)                #Used to find the SQUARE ROOT of Variable G

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [62]:
H = np.array([-2, -3.2, 0.5, 1.2, -4])

In [63]:
np.add(G, H)

array([-2. , -2.2,  2.5,  4.2,  0. ])

##  Indexing, Slicing and Iterating


### One-dimensionalarrays can be indexed, sliced and iterated over, much like lists and other Python sequences.


In [65]:
a = np.arange(9)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512], dtype=int32)

In [66]:
a[4]

64

In [67]:
a[0]

0

In [70]:
a[8]

512

In [71]:
a[1:6]         # this code is used to print from observation 1 to 6 of variabe a

array([  1,   8,  27,  64, 125], dtype=int32)

#### Multidimensionalarrays can have one index per axis. These indices are given in a tuple separated by commas:


In [72]:
def f(x,y):
    return 20*x+y

In [73]:
b = np.fromfunction(f,(5,5), dtype=int)
b

array([[ 0,  1,  2,  3,  4],
       [20, 21, 22, 23, 24],
       [40, 41, 42, 43, 44],
       [60, 61, 62, 63, 64],
       [80, 81, 82, 83, 84]])

In [74]:
b[2,3]                            #this code is used to find Values for Row 2 , Column 3. 
                                  # Also pls note that python start its count from Zero and not 1. 
                                    #E.g. The row 1 in the above array is row zero here

43

In [75]:
b[0:5,0]

array([ 0, 20, 40, 60, 80])

In [77]:
b[0,0:5]

array([0, 1, 2, 3, 4])

In [78]:
b.shape

(5, 5)

### Iteratingover multidimensional arrays is done with respect to the first axis:


In [81]:
for row in b:
     print(row)

[0 1 2 3 4]
[20 21 22 23 24]
[40 41 42 43 44]
[60 61 62 63 64]
[80 81 82 83 84]


In [82]:
for column in b:
    print(column)

[0 1 2 3 4]
[20 21 22 23 24]
[40 41 42 43 44]
[60 61 62 63 64]
[80 81 82 83 84]


##  Shape Manipulation


### Changing the shape of an array

In [12]:
import numpy as np
k = np.floor (8*np.random.random((4,3)))
print(k)

[[6. 0. 3.]
 [6. 5. 3.]
 [6. 2. 4.]
 [0. 4. 5.]]


In [13]:
k.shape                    ##The function k.shape is used to print the shape of an array

(4, 3)

In [14]:
k.ravel()                    ##the code  k.ravel() is used to change the shape of any array and it will flatten the new array

array([6., 0., 3., 6., 5., 3., 6., 2., 4., 0., 4., 5.])

In [15]:
k.reshape(3,4)                ## The code   .reshape  helps to reshape the array to a specified one

array([[6., 0., 3., 6.],
       [5., 3., 6., 2.],
       [4., 0., 4., 5.]])

In [18]:
k.T                            # The code k.T is used to TRANSPOSE the any array

array([[6., 6., 6., 0.],
       [0., 5., 2., 4.],
       [3., 3., 4., 5.]])

  #### Stacking together different arrays

##### Several arrays can be stacked together along different axes:


In [19]:
j = np.floor (5*np.random.random ((3,3)))
j

array([[2., 4., 2.],
       [1., 1., 0.],
       [1., 0., 3.]])

In [24]:
h = np.floor (3*np.random.random ((3,3)))
h

array([[0., 1., 1.],
       [2., 2., 2.],
       [0., 0., 0.]])

In [29]:
np.vstack ((j,h))   #### This code, vstack  helps user to stack various array together vartically

array([[2., 4., 2.],
       [1., 1., 0.],
       [1., 0., 3.],
       [0., 1., 1.],
       [2., 2., 2.],
       [0., 0., 0.]])

In [30]:
 np.hstack((j,h))                ### This code, vstack  helps user to stack various array together Horizontally

array([[2., 4., 2., 0., 1., 1.],
       [1., 1., 0., 2., 2., 2.],
       [1., 0., 3., 0., 0., 0.]])

##  Splitting one array into several smaller ones


In [42]:
import numpy as np
l = np.floor (8*np.random.random((5,10)))
l

array([[0., 4., 2., 5., 4., 1., 3., 4., 2., 0.],
       [0., 2., 5., 7., 0., 6., 1., 4., 4., 2.],
       [7., 3., 3., 0., 6., 6., 6., 1., 3., 3.],
       [4., 7., 2., 4., 7., 6., 2., 7., 1., 6.],
       [4., 5., 6., 6., 4., 0., 7., 3., 3., 1.]])

In [44]:
np.hsplit(l,10)                   #spliting horizontally

[array([[0.],
        [0.],
        [7.],
        [4.],
        [4.]]), array([[4.],
        [2.],
        [3.],
        [7.],
        [5.]]), array([[2.],
        [5.],
        [3.],
        [2.],
        [6.]]), array([[5.],
        [7.],
        [0.],
        [4.],
        [6.]]), array([[4.],
        [0.],
        [6.],
        [7.],
        [4.]]), array([[1.],
        [6.],
        [6.],
        [6.],
        [0.]]), array([[3.],
        [1.],
        [6.],
        [2.],
        [7.]]), array([[4.],
        [4.],
        [1.],
        [7.],
        [3.]]), array([[2.],
        [4.],
        [3.],
        [1.],
        [3.]]), array([[0.],
        [2.],
        [3.],
        [6.],
        [1.]])]

In [45]:
np.vsplit(l,5)                      ## spliting vertically

[array([[0., 4., 2., 5., 4., 1., 3., 4., 2., 0.]]),
 array([[0., 2., 5., 7., 0., 6., 1., 4., 4., 2.]]),
 array([[7., 3., 3., 0., 6., 6., 6., 1., 3., 3.]]),
 array([[4., 7., 2., 4., 7., 6., 2., 7., 1., 6.]]),
 array([[4., 5., 6., 6., 4., 0., 7., 3., 3., 1.]])]

## Copies and Views

### There are three cases:    1. No Copy at All,             View or Shallow Copy,              Deep Copy


In [46]:
###   Simple assignments make no copy of array objects or of their data.

a = np.arange(8)
b  = a
b is a 


True

In [47]:
b.shape = 2,4
a.shape

(2, 4)

In [54]:
## Python passes mutable objects as references, so function calls make no copy

def f(x):
    print(id(x))

In [53]:
id(a)

2248762308528

###  View or Shallow Copy

In [60]:
c = a.view()
c is a

False

In [61]:
c.base is a         # c is a view of the data owned by a 

True

In [62]:
c.flags.owndata

False

In [64]:
c.shape = 2,4
a.shape

(2, 4)

In [66]:
c[1,3] = 608                       #to insert value 608 into the row 1 and column 3 in the array 
a

array([[  0,   1,   2,   3],
       [  4,   5,   6, 608]])

## Deep Copy


### The copy method makes a complete copy of the array and its data

In [68]:
d = a.copy() 
d is a 

False

In [70]:
d.base is a

False

In [72]:
d[1,1] = 9999
a

array([[  0,   1,   2,   3],
       [  4,   5,   6, 608]])

In [75]:
a = np.arange(int(1e8))
b = a[:100].copy()
del a

## Functions and Methods Overview
